import type { Metadata } from "next";
import localFont from "next/font/local";
import "@fullstack-template/shad-ui/globals.css";
import { env } from "../env";
import Providers from "./_components/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const reactScanEnabled = env.NEXT_PUBLIC_NODE_ENV === "development";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{reactScanEnabled && <script crossOrigin="anonymous" src="//unpkg.com/react-scan/dist/auto.global.js" />}</head>
      <Providers>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
      </Providers>
    </html>
  );
}
